---
title: "budget_analysis"
format:
  docx:
    reference-doc: reference.docx
    
execute:
  echo: false
  message: false
  warning: false
---

**বাস্তবায়ন পরিবীক্ষণ ও মূল্যায়নগের পরিচালন ব্যয় বরাদ্দ বিশ্লেষণ**


```{r path}

library(here)
library(writexl)
library(tibble)
library(dplyr)
library(tidyverse)
library(flextable)

if (here() == "C:/Users/bmani/GitHub/budget-r-imed") {
  drive <- "C:/Users/bmani/OneDrive/Finance Division/tripartite_meeting26/115 IMED/"
  # font_path <- "C:/Users/bmani/AppData/Local/Microsoft/Windows/Fonts/"
  
} else if (Sys.getenv("USERNAME") == "Shihab") {
  
  drive <- "C:/Users/User/OneDrive/Finance Division/tripartite_meeting26/115 IMED/"
  # font_path <- "C:/Users/Md. Mamunul Karim/AppData/Local/Microsoft/Windows/Fonts"
  
} else {
  "Device Not available"
}

```





```{r table}

set_flextable_defaults(font.family = "NikoshBAN")

budget <- readRDS(here("data/final/budget_df.rds"))

# write_xlsx(budget, paste0(drive, "data/budget_inputxxxx.xlsx"))
fd <- readxl::read_xlsx(paste0(drive, "data/budget_input.xlsx"))
budget$fd_advice = fd$fd_advice

## generate a table for the operating budget analysis

df_table <- tibble(
  desc = character(),
  budget25_26 = numeric(),
  corrected25_26 = numeric(),
  budget26_27 = numeric(),
)

df_table <- budget %>% filter(type == 1)

## sum rows for budget assistance to BPPA

bppa_total <- df_table %>% 
  filter(activity_code == "131021401") %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))


bppa_total$code_name <- "বাজেট সহায়তা"

df_table <- df_table %>% 
  filter(inst_code == "1150101103364" & is.na(activity_code))

df_table <- bind_rows(df_table, bppa_total)


df_total <- df_table %>% 
  summarise(
    across(
      where(is.numeric), ~sum(.x, na.rm = TRUE)
    )) 

df_total$code_name <- "মোট:"

df_table <- bind_rows(df_table, df_total)


## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3111"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩১১১: নগদ, মজুরি ও বেতন"

df_table <- bind_rows(group_row, df_table)

#------------------------------


## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3211"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২১১: প্রশাসনিক ব্যয়"

pos <- 25

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#-------------------------------------------------------------------

## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3221"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২২১: ফি চার্জ ও কমিশন"

pos <- which(grepl("3221101", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------

#-------------------------------------------------------------------

## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3231"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৩১: প্রশিক্ষণ"

pos <- which(grepl("3231301", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------



## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3243"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৪৩: পেট্রোল, অয়েল ও লুব্রিকেন্ট"

pos <- which(grepl("3243101", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------



## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3244"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৪৪: ভ্রমণ ও বদলি"

pos <- which(grepl("3244101", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------

## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3255"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৫৫:  মুদ্রণ ও মনিহারি"

pos <- which(grepl("3255101", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------

## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3256"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৫৬: সাধারণ সরবরাহ ও কাঁচামাল সামগ্রী"

pos <- which(grepl("3256106", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------

## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3257"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৫৭:  পেশাগত সেবা, সম্মানী ও বিশেষ ব্যয়"

pos <- which(grepl("3257101", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------


## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3258"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩২৫৮:  মেরামত ও সংরক্ষণ"

pos <- which(grepl("3258101", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------


## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "3911"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৩৯১১: সংরক্ষিত"

pos <- which(grepl("3911111", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------

## insert group rows
group_row <- df_table %>%
  filter(
    substr(economic_code, 1, 4) == "41"
  ) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE)))
group_row$code_name <- "৪১: অআর্থিক সম্পদ"

pos <- which(grepl("4111309", df_table$economic_code))

df_table <- bind_rows(
  slice(df_table, 1:(pos-1)),
  group_row,
  slice(df_table, pos:n())
)
#------------------------------------------------------------------------



df <-df_table %>% mutate(
  desc = if_else(is.na(economic_code), code_name, paste(economic_code, "-", code_name)),
  # desc = paste(economic_code, "-", code_name),
  additional = budget26_27 - corrected25_26,
  percent_increase = (budget26_27/corrected25_26-1)*100,
  comment = ""
  ) %>% select(c(desc, budget25_26, corrected25_26, budget26_27, additional,
               percent_increase, fd_advice, comment))






ft <- flextable(df)

ft <- delete_part(x = ft, part = "header")
ft <- add_header_row(
  ft,
  values = c("বিবরণ",
             "বাজেট ২০২৫-২৬",
             "সংশোধিত বাজেট ২০২৫-২৬",
             "প্রাক্কলন ২০২৬-২৭",
             "অতিরিক্ত দাবি (সংশোধিত বাজেটের তুলনায়)",
             "বৃদ্ধি (%) (সংশোধিত বাজেটর তুলনায়)",
             "অর্থ বিভাগের সুপারিশ",
             "মন্তব্য"
            ))

ft <- font(
  ft,
  fontname = "NikoshBAN",
  part = "header"
)

ft <- font(
  ft,
  fontname = "NikoshBAN",
  part = "body"
)

ft <- colformat_double(
  ft,
  j = 2:7,
  digits = 2,
  big.mark = ","
)

ft <- colformat_double(
  ft,
  j = 6,
  digits = 2,
  big.mark = ",",
  suffix = "%"
)



## column width setup
ft <- width(ft,
  j = c(1:8),
  width = c(
    1.7,  # বিবরণ (wide text)
    0.7,  # বাজেট
    0.7,  # সংশোধিত বাজেট
    0.7,  # প্রাক্কলন
    0.7,  # অতিরিক্ত দাবি
    0.7,  # বৃদ্ধি %
    0.7,  # সুপারিশ (text)
    0.5   # মন্তব্য (text heavy)
  )
)

ft <- bold(
  ft,
  i = grepl(":|বাজেট সহায়তা", df$desc),
  bold = TRUE
)

ft <- padding(
  ft,
  i = grepl("-", df$desc),
  j = "desc",
  padding.left = 15,
  part = "body"
)


ft

```

